POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Bartosz Ciechanowski",
  "author": "Bartosz Ciechanowski",
  "url": "https://ciechanow.ski/",
  "likes": "231"
}

// add blog with an attached user
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "New blog with an attached user",
  "author": "Check the user ID",
  "url": "www.google.com",
  "userId": "62c84ab784a312ce009e0f79"
}

// add second blog for previous user
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Second blog!",
  "author": "Check the user ID",
  "url": "https://www.duckduckgo.com",
  "userId": "62c84ab784a312ce009e0f79"
}

// add with token authorization
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyYzg0YWI3ODRhMzEyY2UwMDllMGY3OSIsImlhdCI6MTY1NzI5Njc2N30.pn-3wfs7Lgq9a9fOnTlRX5sXvZOvzkgm0J6uHxrazMk

{
  "title": "Blog posted with authorization!",
  "author": "authorized user",
  "url": "https://www.duckduckgo.com",
  "userId": "62c84ab784a312ce009e0f79"
}