POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "superuser",
  "password": "secret"
}

// test minLength for username
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "u",
  "name": "superuser",
  "password": "secret"
}

// test minLength for password
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "newUser",
  "name": "user",
  "password": "s"
}