// successful
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "secret"
}

// unssuccessful
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "mluukkai",
  "password": "secret"
}