PUT http://localhost:3001/api/notes/62be07ec88b71704bc60be46
Content-Type: application/json

{
    "important": false
}

###
PUT http://localhost:3001/api/notes/62be07ec88b71704bc60be46
Content-Type: application/json

{
    "important": true
}