// Correct entry
POST http://localhost:3001/api/diaries
Content-Type: application/json

{
  "date": "2020-1-4",
  "weather": "sunny",
  "visibility": "great",
  "comment": "smoothest landing of the year"
}

###
// Incorrect entry
POST http://localhost:3001/api/diaries
Content-Type: application/json

{
  "date": "2020-1-4",
  "weather": "sunny",
  "visibility": "awesome!",
  "comment": "smoothest landing of the year"
}